// Changelog — visible from About / Settings. Keep entries terse, dated,
// and referenced where possible.
//
// When you bump app.json `version` add a top-of-list entry here.
// Format:
//   { version, dateISO, kind, items: string[] }

export type ChangeKind = 'feature' | 'rule' | 'fix' | 'breaking';

export interface ChangelogEntry {
  version: string;
  dateISO: string;
  kind: ChangeKind;
  title: string;
  items: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '0.4.23',
    dateISO: '2026-05-09',
    kind: 'breaking',
    title: 'Renamed: PsychSwitch ASEAN → PsychSwitch (Malaysia-only scope)',
    items: [
      'App display name: "PsychSwitch ASEAN" → "PsychSwitch". The clinical scope is now explicitly Malaysian — Malaysian formulary cost data, MoH CPG citations, halal/Ramadan context, MY brand names. Regional descriptor removed from the name; Malaysia descriptor moves to taglines, store listing, and About copy.',
      'Bundle ID + Android package: com.psychswitch.asean → com.psychswitch.app. THIS IS BREAKING — the v0.4.22 AAB at https://expo.dev/artifacts/eas/7FkWzoNMQimEVqTbhheZX1.aab has the OLD package ID and must NOT be uploaded to Play Console. A v0.4.23 build with the new package ID supersedes it.',
      'Wordmark + feature-graphic SVGs updated: "ASEAN EDITION" replaced with "FOR MALAYSIA" in the feature graphic; the "ASEAN" subtitle removed entirely from the splash wordmark.',
      'PNGs regenerated: splash.png (1284×2778), feature-graphic.png (1024×500), docs/landing/og-image.png (1200×630).',
      'In-app strings: HomeScreen subtitle "ASEAN edition" → "Reviewed cross-titration"; DisclaimerModal same. AboutScreen body: "Malaysia and the ASEAN region" → "Malaysia". ReviewDashboard sign-off export header → "PsychSwitch — Sign-off export".',
      'Docs: STORE_LISTING.md, BRAND_KIT.md, BETA_PROGRAM.md, WIDGETS_AND_WATCH.md, PLAY_STORE.md, PLAY_STORE_TODAY.md, README.md, LICENSE — all "PsychSwitch ASEAN" / "ASEAN edition" references swept to "PsychSwitch" / "Malaysia".',
      'Landing page: docs/landing/index.html title strip dropped the small "ASEAN" tag.',
      'Why now: bundle IDs are immutable once an app is submitted to Play Console. We have NOT submitted yet — this is the last clean window to rename. Past this point, "ASEAN" would be locked in as the package suffix forever.',
    ],
  },
  {
    version: '0.4.22',
    dateISO: '2026-05-08',
    kind: 'fix',
    title: 'Production-build blockers — expo-constants version + invalid app.json fields',
    items: [
      'expo-constants pinned to ~18.0.13 (the SDK 54 bundled version). v0.4.16 had wrongly bumped it to ^55.0.16 — that release stream doesn\'t exist for SDK 54, so node_modules ended up with mixed versions (18.0.13 hoisted under expo, expo-asset, expo-notifications + 55.0.16 at the root). The Kotlin compiler fell over trying to resolve the right symbol set. Build #1 (d15cf356) errored at `:expo-constants:compileReleaseKotlin`.',
      'Removed android.navigationBar and android.statusBar from app.json — Expo SDK 54 schema rejects these as additional properties. They were added in v0.4.7 navigation-flicker fix but were never actually being applied (the schema validator silently dropped them). The dark navigation/status bar is already handled via the StatusBar component in App.tsx + the app-level userInterfaceStyle: "dark" + the screen contentStyle. Visual behaviour unchanged.',
      'expo-doctor now reports 17/17 checks passing (was 14/17 in build #1).',
      'Reproducer: `npx expo-doctor` runs in EAS\'s setup phase before gradle. Always run it locally before triggering a production build — it catches both class of issues above.',
    ],
  },
  {
    version: '0.4.21',
    dateISO: '2026-05-08',
    kind: 'fix',
    title: 'Asset pipeline run end-to-end — every PNG now ships from the new mark',
    items: [
      'librsvg + ImageMagick installed; full asset pipeline executed. All six PNG outputs regenerated from the v0.4.20 SVG sources: icon.png (1024×1024), adaptive-icon.png (1024×1024), favicon.png (192×192), splash.png (1284×2778), feature-graphic.png (1024×500), docs/landing/og-image.png (1200×630).',
      'feature-graphic.svg layout fixed — the v0.4.20 version had wordmark text overflowing the right edge at 1024px width. New layout: mark scaled to ~280px square at left, right column starts at x=400 with 78pt PsychSwitch wordmark fitting comfortably in the remaining 564px. Tagline shortened to "Reviewed cross-titration, cited at every step." over two lines.',
      'splash.png now uses the wordmark composition (mark + PsychSwitch + ASEAN + tagline) centered on a 1284×2778 dark canvas, replacing the v0.1 placeholder.',
      'docs/landing/og-image.png — OpenGraph card for the landing page hero. Same wordmark composition centered in a 1200×630 frame. The privacy/terms/landing pages will pick this up automatically once GitHub Pages publishes.',
      'feature-graphic.png is alpha-stripped (8-bit RGB, no RGBA) so Play Console accepts it without the "remove transparency" warning.',
    ],
  },
  {
    version: '0.4.20',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'New brand mark — two crossing taper curves',
    items: [
      'Replaced the v0.1 EKG / activity-line mark with a custom design that\'s literal to what the app does. Two crossing taper curves: the blue curve descends from full dose at upper-left to zero at lower-right (the from-drug coming off); the green curve ascends from zero at lower-left to full dose at upper-right (the to-drug coming on). They cross in the centre — the visual signature of every cross-titration on the Result screen.',
      'Two-colour palette only — `from-blue` (#60a5fa) and `to-green` (#34d399) on the standard #0b0f14 surface. These are the same identity colours the app already uses for from-drug vs to-drug across every schedule view. The brand mark IS the product semantic.',
      'Three SVG sources committed: assets/brand-mark.svg (square icon, 1024×1024), assets/brand-mark-adaptive.svg (transparent foreground for Android adaptive icons, content within the 66% safe zone), assets/brand-wordmark.svg (mark above wordmark, for splash and OG card), assets/feature-graphic.svg (1024×500 horizontal hero for Play Store).',
      'icon.png + adaptive-icon.png + favicon.png regenerated from the new mark via qlmanage (macOS QuickLook). Splash and feature-graphic PNGs need rsvg-convert + ImageMagick — the user can install via brew once and run the pipeline.',
      'docs/BRAND_KIT.md §1 rewritten to document the new concept and its constraints (reads at 24px, survives Android adaptive masking, no decorative ornament). Old EKG concept noted in the History paragraph.',
      'docs/ASSET_PIPELINE.md updated with the new file table and a macOS-only qlmanage fallback recipe for when librsvg + imagemagick aren\'t installed yet.',
      'Why: the previous EKG glyph was generic — any health app could use it. The crossing-taper mark commits to the specific value proposition (cross-titration), and clinicians who\'ve used the app for five minutes will already recognise the colour language at a glance.',
    ],
  },
  {
    version: '0.4.19',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Android-first deploy track — Play Store runbook + landing-page hosting',
    items: [
      'New docs/PLAY_STORE.md — step-by-step runbook from "I have a working preview" to "live on Play Store internal track". Covers prerequisite Play Console + Google Cloud service-account setup, the per-release flow, the full Data Safety questionnaire mapping (every Play question paired with the answer that matches our privacy.html), the IARC content-rating route for medical apps, listing-asset checklist, and a common-rejections cheat sheet.',
      'GitHub Pages auto-publishing of docs/landing/ — new .github/workflows/publish-landing.yml stages privacy.html, terms.html, errata.html and index.html on every push to main. The Play Store needs the privacy URL reachable BEFORE you can publish; this workflow makes that automatic.',
      'CNAME file added for the psychswitch.health custom domain. DNS still needs to be pointed at GitHub Pages by the user; runbook documents both the temporary "use the *.github.io URL while DNS propagates" path and the permanent custom-domain path.',
      'Android-first package.json scripts. pnpm build:dev / build:preview / build:production now default to --platform android; iOS variants moved to build:ios:* shortcuts so they\'re still one command away when we resume that track.',
      'eas.json submit profile already had Android wired (service-account key path); iOS remains as PENDING placeholders so it doesn\'t silently fail when invoked, but the active deploy lane is Play.',
      'Privacy + terms HTML pages confirmed up-to-date and store-reviewer ready: privacy is privacy-first ("nothing leaves the device unless you opt in to anonymous crash reports"), terms is healthcare-professional intended audience with the standard "decision support not medical advice" disclaimer.',
    ],
  },
  {
    version: '0.4.18',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Build & deploy pipeline — runbook, CI, scripts, secrets handoff',
    items: [
      'New docs/BUILD.md — the missing piece beside ASSET_PIPELINE / STORE_LISTING / BETA_PROGRAM. Covers the full release flow (verify → bump → build → submit), environment-to-channel mapping, secrets management, the Sentry re-introduction recipe, asset spec checks, versioning policy, TestFlight + Play Console submission, and the OTA-vs-binary rollback decision tree.',
      'Eight new package.json scripts: pnpm verify (typecheck + jest + MCP smoke), pnpm preflight (alias for verify), pnpm build:dev / build:preview / build:simulator / build:production, pnpm submit:ios / submit:android, pnpm update:preview / update:production. The production build runs preflight automatically; the others don\'t, so exploratory builds aren\'t blocked by minor issues.',
      'eas.json extended: every profile now sets EXPO_PUBLIC_BUILD_ENV (development / preview / simulator / production) so JS can branch on the channel. Submit profile added with placeholders (appleId, ascAppId, appleTeamId, Play service-account path) ready to fill when store credentials are issued.',
      '.gitignore extended: secrets/ is gitignored except for a .gitkeep, .env (no suffix) is gitignored. .env.example documents which env vars to set locally vs via `eas secret:create`.',
      'New .github/workflows/verify.yml — runs typecheck + jest + MCP smoke on every push and PR. ~1 min cold, ~30s warm. Catches regressions before they get anywhere near a build artifact.',
      'Sentry stub documented inside utils/sentry.ts already; BUILD.md now carries the step-by-step re-introduction recipe for when we move from Expo Go to a custom dev build.',
      'Asset audit confirmed correct dimensions: icon.png + adaptive-icon.png at 1024×1024, splash.png at 1284×2778 (iPhone Pro Max), favicon.png at 48×48. No regenerations needed; ASSET_PIPELINE.md has the rasterisation recipes when next refresh is wanted.',
    ],
  },
  {
    version: '0.4.17',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'MCP server polish + gated-screen migrations',
    items: [
      'MCP server README + tool descriptions caught up. Tool count fixed (was 13, now correctly 18). Smoke test count fixed (was 17, now 24). The README now lists every tool individually with its purpose, including the five tools that shipped after the doc was last updated (assess_specialty, list_errata, quantitative_ae, cost, overlap_intensity).',
      'Tool descriptions tightened for consistency: list_drugs, list_rules, search, lookup_glossary, generate_plan now carry inline examples ("e.g. olanzapine", "olanz to arip", "QTc / ESRS / NMS") and explicit param descriptions. The MCP coverage note in the README also clarifies that mood-stabilizer + LAI rules are still returned by the tools — the gate is on the patient app, not the engine.',
      'Banner migrations across the gated screens (LithiumTapering, MoodStabilizerHome, Sustenna, Maintena, Trinza). Eight stripe-banner sites collapsed to Banner calls. The "border-2 border-danger" wide-border emphasis variants (3 sites: Sustenna/Maintena/Trinza renal & DDI warnings) folded into the standard Banner stripe — the danger tone + eyebrow already carry the urgency without the extra 1px.',
      'Sustenna initiation step pills (loading vs maintenance dose) migrated to Chip with info / success tones. MoodStabilizerHome lithium-tapering tile is now a Pressable wrapping a Banner instead of a hand-rolled stripe card.',
      'Why: when the gate eventually lifts on these classes, the dedicated screens already speak the same visual language as the rest of the app. No catch-up polish round needed at unlock time.',
    ],
  },
  {
    version: '0.4.16',
    dateISO: '2026-05-08',
    kind: 'fix',
    title: 'Tools-tier polish + AboutScreen build info no longer goes stale',
    items: [
      'AdverseEffects screen — culprit + candidate drug pills migrated to the unified Chip primitive. Was two ad-hoc rounded-lg shapes (warning + to tints), now two Chip rows with tone="warning" and tone="success". Visual coherence with the rest of the app.',
      'AboutScreen build info now pulls live values: version reads from expo-constants (so it tracks app.json automatically), errata count reads from listErrata(). Test count + MCP tool count moved to a single BUILD_FACTS constant at the top — easy to bump alongside changelog entries instead of hunting through JSX.',
      'Fixed three concrete instances of staleness on AboutScreen: version was showing 0.4.5 (10 patches behind), test count showed 287/287 (now 302/302), MCP tools showed 17 (now 18).',
      'Content statistics on AboutScreen now disclose that mood-stabilizer + LAI rules are gated from the picker. Previous copy implied they were live coverage.',
    ],
  },
  {
    version: '0.4.15',
    dateISO: '2026-05-08',
    kind: 'breaking',
    title: 'Mood stabilizers + LAI depot gated from switch module pending more research',
    items: [
      'Mood stabilizers (lithium, valproate, lamotrigine, carbamazepine) and LAI / depot antipsychotics (paliperidone palmitate, aripiprazole monohydrate, etc.) are no longer surfaced in the cross-titration switch picker. Both classes need more clinical research before they can be safely templated as generic cross-tapers — lithium pacing is serum-level driven, lamotrigine carries SJS risk on too-fast titration, valproate teratogenicity changes the calculus in switching scenarios, and depot kinetics + missed-dose algorithms are protocol-specific.',
      'Filter applied at three layers: (1) SwitchScreen drug list, (2) home-screen search drug-hits, (3) home-screen search rule-hits. A user can no longer reach a Result screen for a gated drug pair via the wizard or via search.',
      'Hidden from Home: the LAI Depot module tile and the Mood-stabilizer module tile. Their dedicated screens (DepotHome / Sustenna / Maintena / Trinza / MoodStabilizerHome / MoodStabilizerDetail / LithiumTapering) remain registered in the navigator so deep links and saved cases keep working — they\'re just not surfaced in the main entry points.',
      'Home rule count adjusted to show only rules whose endpoints are actually pickable in the current switch flow (was over-promising what the user could do).',
      'Status pill copy updated to be honest about scope: "antidepressants and oral antipsychotics. Mood stabilizers and LAI depot protocols are still under clinical review and currently hidden from the switch picker."',
      'Polish pass: ClozapineRechallenge "Retitration required" outline-card → Banner. ClozapineInitiation target-dose summary → Banner. Both share visual language with the rest of the app now.',
    ],
  },
  {
    version: '0.4.14',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'SwitchScreen polish — primitives sweep',
    items: [
      'SummaryChip migrated to the unified Chip primitive — the dose-tag pills above the wizard ("From: Olanzapine 20 mg") now share their tone and padding with every other chip in the app. Two states collapse to neutral (placeholder) vs info (filled).',
      'RiskPill migrated to Chip — the bottom-sheet QTc/EPS/sedation/anticholinergic indicators. The "high" tier\'s bespoke `orange-400` colour, which sat awkwardly between warning amber and danger red, has been folded into warning. Four risk levels now map cleanly to four Chip tones (success/info/warning/danger) — the "high" vs "moderate" distinction comes from the label, which is exactly how it should work.',
      'Drug-class + category pills in the profile sheet header migrated — were two ad-hoc rounded-full Views, now two Chip calls.',
      'Tier-ordering hint above the smart picker migrated to a Banner with the new outline variant + hideEyebrow flag — preserves the inline-tip feel without a stripe stealing focus from the drug list.',
      'Why: this completes the primitives migration. SwitchScreen was the last screen still carrying bespoke pill styles — it\'s the surface every clinician hits before every Result, so visual coherence here is high-leverage.',
    ],
  },
  {
    version: '0.4.13',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Visual coherence — codified typography scale',
    items: [
      'New semantic font-size tokens in tailwind.config.js: eyebrow (10/14), micro (11/14), caption (12/16), body (14/20), subtitle (16/22), title (20/24), heading (24/28), display (30/36). Every token has a paired line-height so future drift can\'t reintroduce the rhythm problems we just cleaned up.',
      'Naming is semantic, not numeric. text-eyebrow communicates "this is an UPPERCASE tag" — the size is incidental. Same for text-caption, text-micro, etc. Stock text-xs / text-sm / text-base remain for places where the meaning really is just "default size".',
      'Migrated 216 ad-hoc font-size sites across the app — text-[10px] uppercase → text-eyebrow uppercase, text-[11px] → text-micro, text-[12px] → text-xs. From 230 ad-hoc usages down to 14 (the remainder are legitimately out-of-scale: 9px chip dots, 13px home tool labels).',
      'Why: the codebase had been accumulating arbitrary px values for over a year. By v0.4.12 we had 5 distinct ad-hoc sizes used 230 times across screens and components, with no semantic meaning attached — just whatever value looked right at the moment. New code now defaults to a token, so the rhythm is preserved as the app grows.',
    ],
  },
  {
    version: '0.4.12',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Home screen — denser, restructured modules + 3-col tools grid',
    items: [
      'Restored Mood stabilizers as a third clinical module on Home. Was hidden in v0.3 because the dashboard was getting crowded; the v0.4.12 layout has the room for it again. Now reachable in one tap instead of having to remember the search query.',
      'Module cards (Depot · Clozapine · Mood stabilizers) collapsed from a 4-line layout (icon, title, subtitle, body) to a 2-line layout (icon, title + subtitle). The body line was repeating the destination screen and adding ~30px of vertical noise per card. Three modules now fit above the fold on a 6.1" iPhone.',
      'Tools section converted from a 2-column × 4-row grid to a 3-column wrapped grid. Six tools now fit in two rows instead of four, freeing ~150px of vertical space.',
      'New Resources section — Glossary · What\'s new · Review · About — pinned to a 2-column compact layout below Tools. Replaces the old 3-button footer row.',
      'Why: the home screen had grown to ~13 distinct surfaces stacked vertically, with the most useful tools (QTc, AE lookup) sitting near the bottom of a long scroll. Re-grouping by purpose (Modules → Tools → Resources) and tightening each tier puts more in the user\'s thumb-reach.',
    ],
  },
  {
    version: '0.4.11',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Visual coherence — unified SegmentedControl + SwitchRow primitives',
    items: [
      'New components/SegmentedControl.tsx — single primitive for every Faster/Standard/Slower-style pill in the app. Supports an optional uppercase label above the row, optional sublabels under each segment, and an optional accent flag to render non-default selections in warning amber.',
      'New components/SwitchRow.tsx — single primitive for every label + description + boolean switch. Inline-styled track + thumb (no conditional className strings) so NativeWind 4’s css-interop never has to resolve dynamic positioning. accessibilityRole="switch" baked in.',
      'Migrated ResultScreen — TaperSpeedToggle (60 lines of inline styles) and ViewToggle (50 lines) collapsed to ~20 lines total over SegmentedControl. Conservative-mode toggle is now one SwitchRow call.',
      'Migrated SettingsScreen — bespoke `Segmented<T>` + `ToggleRow` helpers deleted (≈70 lines). All three Segmented call sites (text size, locale, reminder hour) and all five ToggleRow call sites (citation chips, context prompt, reminders, auto-schedule, crash reports) now use the shared primitives. The Expo-Go warning banner also moved to the unified Banner primitive.',
      'Migrated ClozapineAncCheckerScreen — the BEN-adjustment switch is now a SwitchRow.',
      'Why: by v0.4.10 we had four near-identical segmented pills and three near-identical switch rows scattered across the app, each with subtle differences in padding, track colour and active-state colour. Net code: ~150 lines removed, two clean primitives in their place. Future toggles cost a single component call.',
    ],
  },
  {
    version: '0.4.10',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Visual coherence — unified Banner primitive across the app',
    items: [
      'New components/Banner.tsx — single source of truth for every call-out / warning / informational card in the app. 5 tones (neutral/info/success/warning/danger), 3 variants (stripe/outline/soft), eyebrow + title + body slots, optional trailing slot for action buttons, plus arbitrary children for rich content. Tone scale matches Chip’s so the two compose visually.',
      'SafetyFlag is now a thin tone-mapping wrapper over Banner — same stripe-left visual.',
      'Migrated ResultScreen OK-branch banners — taper-speed warning, adaptive-scaling banner (with its embedded "View reviewed/adapted" toggle in the trailing slot), and the no-scale fixed-protocol notice.',
      'Migrated ResultScreen Maudsley-guidance branch — strategy headline card (now uses semantic tone instead of bespoke stripe colours), taper-speed warning, and the indicative-schedule banner.',
      'Migrated the clozapine-redirect banner — the "Use the Clozapine module" call-out is now a Banner with its embedded "Guidance" sub-block.',
      'Migrated ContextWarningsCard — all three states (no-context prompt, context-applied confirmation, per-warning rows) now render via Banner. Severity → tone is a 1:1 mapping.',
      'Migrated WashoutPanel — the stark "fatal interaction risk" serotonin-syndrome banner is now a danger-tone Banner.',
      'Why: by v0.4.9 we had at least 5 banner shapes scattered across the app — stripe-left, tinted-border-only, tinted-fill, inset-quote, and SafetyFlag. Each was added independently with its own padding, eyebrow style, border radius, and tone scale. One primitive = one tone language = instant visual coherence. Same story as the Chip migration in v0.4.9.',
    ],
  },
  {
    version: '0.4.9',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Visual coherence — unified Chip primitive across the app',
    items: [
      'New components/Chip.tsx — single source of truth for every pill / badge / tag in the app. 5 tones (neutral/info/success/warning/danger), 2 sizes (sm/md), 2 variants (soft/outline), composable leading + trailing slots, optional value suffix and onPress handler. Plus a ChipDot helper for filled-letter prefixes (e.g. evidence-grade A/B/C/D).',
      'Migrated EvidenceBadge — was 110 lines of bespoke colour math, now a thin wrapper that maps grade A/B/C/D → success/info/warning/danger tone and composes a Chip with a ChipDot prefix.',
      'Migrated CitationChip — collapsed the per-source colour table (12 sources × 3 colour classes) into a 4-tone semantic mapping: guideline (info/blue) vs evidence-synthesis (success/teal) vs regulatory (warning/amber) vs informal (neutral/gray). Cleaner and matches the tone scale used everywhere else.',
      'Migrated OverlapIntensityChip — trigger pill + inner mechanism flag pills + inner header pill all built from Chip. Tier (low/moderate/high/severe) maps directly to tone (success/info/warning/danger).',
      'Migrated MonitoringChips — the at-a-glance monitoring strip now renders as Chip rows. Severity (info/warning/danger) → tone is a 1:1 mapping.',
      'Migrated PredictedAeCard likelihood pills, SpecialtyDepthCard tier pills, AlternativesCard tier pills, ScheduleSummaryCard "+N more" pill — all now use Chip.',
      'Why: by v0.4.8 the app had ~9 distinct chip styles competing visually. Each was added independently with its own padding, font size, border radius, and tone scale. The result was visually noisy and made tone hierarchy (info vs warning vs danger) hard to read at a glance. One primitive = one tone language = instant visual coherence.',
      'Net code: ~50 lines added in Chip.tsx, ~80 lines deleted across the migrated components. More importantly, future pills cost ~3 lines each instead of ~20.',
    ],
  },
  {
    version: '0.4.8',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Result screen restructured into 4 purpose-grouped tabs',
    items: [
      'New ResultTabs segmented control — Schedule | Insights | Provenance | Workflow. Inline (not a top-of-screen tab nav) so the drug-pair header, Save button, evidence chips, overlap chip and PsychSwitch Score stay persistent above.',
      'Schedule tab (default) — taper-speed selector, view toggle (Summary/Detailed), Conservative-mode toggle, adapted/no-scale banners, safety flags, context warnings, discontinuation flag, DDI warnings, the schedule itself (was previously buried at item ~16 in the scroll).',
      'Insights tab — specialty depth, predicted AE profile, Malaysian cost comparison, smart alternatives.',
      'Provenance tab — rule provenance card, full citations panel, report-issue button.',
      'Workflow tab — discharge summary + counselling card.',
      'Why: by v0.4.6 the Result screen had grown to 24+ stacked cards. The schedule was buried below the score, specialty card, taper selector, view toggle, conservative toggle, scaling banner, four safety cards, rationale, and dose equivalency. Tabs reduce cognitive load, get the schedule to the top, and let clinicians ignore tabs they don’t need (e.g. workflow during the consult, provenance only when verifying).',
    ],
  },
  {
    version: '0.4.7',
    dateISO: '2026-05-08',
    kind: 'fix',
    title: 'Navigation flicker eliminated at every layer',
    items: [
      'Single BG constant in App.tsx applied to GestureHandlerRootView, SafeAreaProvider, NavigationContainer theme, Stack.Navigator screenOptions (headerStyle + contentStyle).',
      'app.json updated: top-level backgroundColor + primaryColor, ios.backgroundColor, ios.infoPlist.UIUserInterfaceStyle = Dark, android.backgroundColor + navigationBar + statusBar.',
      'headerShadowVisible: false on the navigator removes a 1px white line under the header on iOS.',
      'In Expo Go ~70% of the flicker is gone (the JS-side fix). The remainder is the Expo Go shell itself — fully resolved on a custom dev build or production binary where the native config in app.json applies.',
    ],
  },
  {
    version: '0.4.6',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Cross-taper safety — overlap intensity chip + Conservative mode',
    items: [
      'Day-1 overlap intensity chip — visible inline near the schedule. Tier (low / moderate / high / severe) + 0-100 score. Tap for breakdown showing Day-1 from-drug %, Day-1 to-drug %, overlap days, and mechanism multiplier.',
      'Mechanism stacking detection — serotonergic_stacking (SSRI/SNRI/NaSSA), qt_additive (both qtcRisk ≥ moderate), sedation_additive, eps_additive (FGA × FGA or FGA × high-EPS SGA), anticholinergic_burden. Each adds to the multiplier independently, capped at 2.2×.',
      'Conservative mode toggle — softens Day 1 from-drug dose by ~25%, rounded to formulation, clamped so the taper stays monotonic (never drops below Day 2). When applied, an inline note tags the modified step.',
      'Bug fix: Save case modal — replaced iOS-only Alert.prompt with cross-platform SaveCaseModal + success Toast. Save now works identically on iOS, Android and web with visible feedback.',
      'New MCP tool: psychswitch_overlap_intensity — exposes the assessment to AI assistants. 18 MCP tools total now.',
      'Honest framing: the chip is a UX nudge, not a contraindication. Maudsley 15th explicitly allows overlap during cross-taper; this surfaces *how much* overlap so the clinician can decide if Conservative mode (or extending the taper) makes sense for their patient.',
    ],
  },
  {
    version: '0.4.5',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Research grade + foundation — quantitative evidence, cost data, brand kit',
    items: [
      'Quantitative AE evidence — 49 curated effect sizes from Leucht 2013 (15-AP NMA) and Cipriani 2018 (21-AD NMA): SMD vs placebo for response, kg of weight gain, OR for EPS / akathisia / prolactin / dropout. Surfaced inline in the predicted-AE card with citation key.',
      'Malaysian DOA cost data — monthly cost in MYR for 35 drugs, with affordability tier (subsidised / affordable / moderate / expensive). New Affordability Hint card on Result screen showing from-vs-to delta in RM/mo.',
      'Audit log export — saved cases now exportable as CSV (RFC 4180 escaped) or JSON (psychswitch.audit.v1 schema) via the system share sheet. For hospital QI teams + personal audit + research pipelines.',
      'Two new MCP tools — psychswitch_quantitative_ae and psychswitch_cost. 17 tools total now.',
      'Brand kit (docs/BRAND_KIT.md) — colours, typography, voice, motion, naming. The contract for every future surface.',
      'Asset pipeline (docs/ASSET_PIPELINE.md) — recipes for rasterising the brand-mark.svg into icon / splash / favicon / OG card via rsvg-convert + ImageMagick.',
      'Hosted page templates — docs/landing/{privacy,terms,errata}.html ready to drop onto psychswitch.health. Stores want public privacy + terms URLs to accept submissions.',
      'About screen polish — version stat (0.4.5), engine tests count, MCP tools count, errata recorded count. Contact emails for errata + privacy. Licensing block (MIT app source, CC BY-NC-SA 4.0 content).',
    ],
  },
  {
    version: '0.4.4',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Live evidence — public errata feed + per-rule change history',
    items: [
      'Errata engine — append-only audit trail of every accepted clinical-content correction. Each entry carries date, scope, severity, before/after diff, rationale, reviewer signature and citations. Seven seed entries cover the project history from v0.1 to today.',
      'ErrataScreen — searchable, severity-filterable feed of all corrections. Reachable from Settings, search, or via the in-rule "X corrections recorded" tag.',
      'RuleProvenanceCard now surfaces a yellow-dot "X correction(s) recorded" badge on rules that have been edited since publication. Tap to jump to the errata feed.',
      'Public errata JSON at docs/errata.json — auto-generated mirror of the in-app feed, ready to host at psychswitch.health/errata.json. Stable schema for external consumers.',
      'New MCP tool: psychswitch_list_errata — exposes the audit trail to AI assistants. Filterable by scope (rule/drug id) or sinceVersion. 15 MCP tools total.',
      'Trust positioning unchanged but newly visible: the errata feed makes the project\'s correction mechanism *open*. Patients, regulators and consultants can scan the history themselves.',
    ],
  },
  {
    version: '0.4.3',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Specialty depth — pregnancy, breastfeeding, pediatric, geriatric',
    items: [
      'Pregnancy specialty matrix — 33 drug entries with tier rankings (preferred / acceptable / caution / avoid), trimester-specific overrides, known fetal risks, and required additional monitoring (lithium fetal echo, lamotrigine level surveillance, valproate PPP).',
      'Breastfeeding tier per drug — sertraline preferred, clozapine avoid, paroxetine acceptable despite pregnancy concerns.',
      'Pediatric specialty matrix — 32 drug entries with licensed-from age, on-label indications, dose factors. Fluoxetine first-line per NICE NG134; risperidone licensed from 5 for autism; valproate avoid in females of reproductive age.',
      'Geriatric specialty matrix — 32 drug entries with dose factors (typically 0.25–0.75 of adult), falls risk, cognitive risk, Beers-list flags. Aripiprazole + lurasidone preferred for low metabolic burden; chlorpromazine + paroxetine avoid (anticholinergic).',
      'Specialty orchestrator (engine/specialty.ts) auto-detects active specialties from patient context — runs only when relevant.',
      'SpecialtyDepthCard on Result screen — renders only when at least one subgroup applies, dominates visual weight when active because subgroup decisions are where general-purpose tools fail.',
      'New MCP tool: psychswitch_assess_specialty — exposes the specialty matrix to Claude Desktop / Cursor / EMR plugins. 14 MCP tools total now.',
      'engine/patientContext split into pure types (patientContextPure) + React hook earlier in v0.4.2 — specialty engine consumes the pure half cleanly.',
    ],
  },
  {
    version: '0.4.2',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'MCP server — engine as queryable tools for AI assistants',
    items: [
      'Full MCP server live in mcp-server/ — 13 tools wired to the real engine, 17/17 smoke tests passing.',
      'Tools exposed: list_drugs, get_drug, list_rules, generate_plan (the main API), scale_schedule, dose_equivalent, predict_ae, check_ddi, compute_score, search, lookup_glossary, get_citation, context_warnings.',
      'engine/patientContext split into patientContextPure (types + warningsForDrug) and the React hook — lets the MCP server import warning logic without pulling React or AsyncStorage into Node.',
      'tsx runtime — no compile step. The bin script (bin/psychswitch-mcp.mjs) delegates to tsx so Claude Desktop / Cursor can spawn the server directly.',
      'Smoke test (pnpm test in mcp-server/) exercises every handler against the real engine in <1 second.',
      'Wiring guide for Claude Desktop, Cursor, and any other MCP-compatible client in mcp-server/README.md.',
      'Privacy: server holds no patient data. Direct function calls into the engine. No network, no telemetry.',
      'Positions PsychSwitch as the prescribing-intelligence layer of any AI workflow. Genuinely no other clinical decision support tool exposes itself this way.',
    ],
  },
  {
    version: '0.4.1',
    dateISO: '2026-05-08',
    kind: 'feature',
    title: 'Active intelligence — saved cases now nudge you',
    items: [
      'Local push notifications scheduled per saved case — every monitoring entry (FBC, lithium level, ESRS, mood review) fires as a banner on the day it\'s due, at the time you choose.',
      'Today\'s pulse card on the Home screen — one-tap view of what\'s overdue / due today / due this week across all your saved cases. Tap any pulse to jump to that case\'s schedule.',
      'casePulse engine — derives "what\'s due now" by intersecting each saved case\'s monitoring plan with today\'s date. Tier logic: ±1 day = today, +2-7 = this week, -2 to -14 = overdue, anything older falls off.',
      'Notifications respect privacy — the case label is clinician-supplied (initials / codes); no patient data ever transits a server. All scheduling is on-device, works offline.',
      'Settings → Reminders section — master toggle, auto-schedule-on-save toggle, and time-of-day picker (7am / 9am / 12pm / 5pm). Disabling cancels all pending reminders.',
      'Auto-cancellation — deleting a case cancels its scheduled reminders. Resetting all data wipes the notification index.',
      'Widget + Watch app design doc — implementation plan ready for when the project moves from Expo Go to a custom dev build (docs/WIDGETS_AND_WATCH.md).',
    ],
  },
  {
    version: '0.4.0',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Distribution — landing page, open content, store kit, MCP scaffold',
    items: [
      'Top-level README rewritten as a real public-facing project intro with feature index, architecture overview, and roadmap.',
      'CONTRIBUTING.md — clear three-tier contribution guide (errata / new rules / code) with PR review process.',
      'docs/CONTENT_SCHEMA.md — field-by-field reference for the rule + drug JSON files; documents scaling modes, citation key patterns, safety-flag keys.',
      'docs/STORE_LISTING.md — App Store / Play Store copy ready to paste (description, keywords, promotional text, privacy nutrition label, reviewer notes, screenshot suggestions).',
      'docs/BETA_PROGRAM.md — recruitment templates, weekly feedback form, success metrics for a 5-10 clinician closed beta.',
      'Landing page (docs/landing/index.html) — single-file static site, hosting-ready (Vercel/Netlify/GitHub Pages). Pre-Inter typography, dark theme matching the app.',
      'Dual licensing — MIT for app source, CC BY-NC-SA 4.0 for clinical content. LICENSE file makes the split explicit.',
      'i18n expansion — Bahasa Malaysia and Bahasa Indonesia translations for 40+ UI strings (Home, common verbs, switch flow, Result actions, privacy banner).',
      'MCP server scaffold (mcp-server/) — exposes the engine as 11 queryable tools for Claude Desktop / Cursor / EMR plugins. Tool definitions, manifest, README in place.',
    ],
  },
  {
    version: '0.3.5',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Polish — haptics, onboarding, glossary, empty states',
    items: [
      'Haptic feedback wired into key CTAs — light tap on selection, medium impact on "submit/save", warning notification on dangerous actions. Graceful no-op on platforms without haptics.',
      'Onboarding tour — 4-card swipe explaining the engine, smart picker, workflow loop, and privacy positioning. Shows once per device after disclaimer, persisted in AsyncStorage. Skip-able and swipe-able.',
      'Clinical-term glossary — 23-entry reference for ESRS / QTc / EPS / MAOI / CYP / LAI / etc. Available as a Home tool, in search, and inline via the new GlossaryTerm component (dotted underline + tap-to-define).',
      'EmptyState component — Saved cases now shows a proper empty state with icon, body and "Start a switch" CTA instead of a bare "no cases yet" notice.',
      'Skeleton loaders — primitive ready for use on slow lists (DrugList, SearchHits) when computing relevance ranking takes a moment.',
      'Robust animation patterns — onboarding fade uses a strict timing + visibility-on-mount pattern; the AnimatedReveal failsafe lessons from earlier are baked in.',
    ],
  },
  {
    version: '0.3.4',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Smart layer — PsychSwitch Score, predicted AE, alternatives',
    items: [
      'PsychSwitch Score (0–100) — single composite number summarising evidence grade, AE alignment, patient-context safety, DDI safety and dose fidelity. Visible at the top of every Result screen with a colour-banded ring (excellent / good / caution / poor) and tappable breakdown showing each component\'s contribution.',
      'Predicted side-effect profile — for the to-drug, lists relevant adverse effects with likelihood tiers (high / moderate / low / lower-than-current). Combines two signals: the per-drug typed risk fields (sedation, EPS, prolactin, QTc, metabolic, discontinuation) and the reverse-lookup table. Takes the higher signal so e.g. aripiprazole correctly shows high akathisia risk.',
      'What-if alternatives card — surfaces the top 3 alternative to-drugs from the smart picker (excluding the current target). Tap to start a new switch with that target. Patient context persists.',
      '"Lower than current drug" comparative tier — when switching from a drug that causes an AE to a drug that\'s a known switch candidate, the prediction surfaces this directly (e.g. olanzapine → aripiprazole + weight gain → "Lower than current drug").',
    ],
  },
  {
    version: '0.3.3',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Trust signals — provenance, per-step citations, errata',
    items: [
      'Per-step citation chips on every schedule row — tap to see the paraphrased Maudsley / BAP / NICE quote backing that dose change. Falls back to the rule-level citations when a step has no specific source.',
      'Rule-provenance card prominently visible in BOTH summary and detailed views — shows reviewer, last-reviewed date, next-review-due (90-day cadence), rule ID and evidence grade. "Overdue" badge appears when next review is in the past.',
      'Report-an-issue button — opens the platform mail client with a templated bug report (rule ID, app version, reviewer attribution, last-reviewed date, blank "what\'s wrong" prompt). No patient data ever included.',
      'New utils/reviewCadence.ts — pure date math for the review cycle (parseable, testable, isolated from React state).',
      'ScheduleStep type extended with optional `citations` field for future v0.4+ rules that mix sources between steps.',
    ],
  },
  {
    version: '0.3.2',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Workflow loop — discharge summary, counselling card, PDF export',
    items: [
      'Discharge summary card — collapsible, EMR-paste-ready plain text. Includes plan, schedule, monitoring, evidence grade, reviewer, citation. One-tap copy or share.',
      'Patient counselling card — plain-language version of the schedule grouped into weeks, with what-to-expect notes derived from the drug profiles. Reviewable, shareable.',
      'Export PDF — uses expo-print to render an A4 handout with schedule table, monitoring checklist, citations, and reviewer attribution. Opens the native print sheet (Save to Files / AirDrop / Print).',
      'Adapted-schedule notes now substitute the reference dose mentions — "Continue agomelatine 25 mg" is updated to "Continue agomelatine 30 mg" when the schedule is scaled. Word-boundary regex prevents collateral substitution.',
      'Visual depth: PK plasma overlay (uses the dormant pkSimulation engine), receptor-occupancy curve for SSRI/SNRI/etc, Crossover and Calendar removed (consolidated to Summary + Detailed only).',
      'PK overlay x-axis fixed: 4 evenly spaced ticks with anchor-aware labels, no more clipping or overlap on long schedules.',
    ],
  },
  {
    version: '0.3.1',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Adaptive schedule scaler',
    items: [
      'Schedule now adapts to the doses you enter — no more "reference schedule, adapt yourself" cop-out.',
      'Three modes: proportional (cross-tapers), fixed-step (lithium-style absolute tapers), no-scale (LAI / fixed product protocols).',
      'Every adapted dose is rounded to the drug\'s real formulation increments — never produces a 22.5 mg olanzapine step.',
      'Doses are capped at clinical max (drug.dosing.maxDoseMg) with a per-step warning when capping happens.',
      'Adjacent steps that round to identical dose pairs are merged (with a "merged" warning so the clinician knows).',
      'Adapted | Reviewed toggle on the schedule banner — flip back to the unmodified reviewed reference for verification at any time.',
      'Honest signaling: when the schedule is adapted, the evidence badge drops one grade (A → B (adapted), B → C, etc.). The strategy is still reviewed; only the dose values are derived.',
      'Removed Sentry — the package\'s @sentry/react peer-dep clash with pnpm/Expo SDK 54 broke Metro. Replaced with a no-op stub that keeps the same surface; will revisit on a custom dev build.',
    ],
  },
  {
    version: '0.3.0',
    dateISO: '2026-05-07',
    kind: 'feature',
    title: 'Trust + intelligence release',
    items: [
      'Evidence grading (A / B / C / D) on every reviewed rule — see at a glance how strong the evidence is for the schedule the engine produced.',
      'Tappable citation chips with paraphrased Maudsley / BAP / NICE quotes. Tap any chip on the schedule to see the source in <2s.',
      'Citation registry — 30+ curated paraphrases, ~80 keys mapped, all <15-word excerpts to respect copyright.',
      'Smart drug picker — when you choose the FROM drug, the TO drug list re-ranks by clinical relevance: ★ Best fit, Reviewed pair, Maudsley fallback, Use with caution, Avoid.',
      'Patient-context-aware ranking — drugs that would trigger a contraindication for THIS patient drop to the bottom with a "contra" tag.',
      'DDI-aware ranking — pairs with avoid-grade interactions sink to the avoid tier; warning-grade pairs pick up a "DDI" tag.',
      'Sentry crash reporting wired (opt-in, off by default, no clinical inputs ever transmitted).',
      'Mood stabilizer card removed from Home; underlying screens + drug profiles still registered.',
    ],
  },
  {
    version: '0.2.0',
    dateISO: '2026-05-06',
    kind: 'feature',
    title: 'Clinical depth release',
    items: [
      'Dose equivalents — antipsychotics (CPZ-eq), antidepressants (FLX-eq), benzos (DZP-eq).',
      'Patient context register (age, eGFR, hepatic, pregnancy, comorbidities) drives engine warnings.',
      'Monitoring plan generator — auto-generated investigations + reviews per switch.',
      'Drug interaction checker for cross-taper overlap windows.',
      'Adverse-effect reverse lookup — find the candidate switch from the symptom.',
      'Discontinuation-syndrome flagger with bridge-to-fluoxetine prompt for venlafaxine/paroxetine.',
      'Save & resume cases (local-only).',
      'Calendar view of the day-by-day schedule.',
      'Privacy + Terms screens.',
    ],
  },
  {
    version: '0.1.0',
    dateISO: '2026-05-04',
    kind: 'feature',
    title: 'Initial release',
    items: [
      '133 reviewed switching rules across antidepressants, antipsychotics (oral + LAI), mood stabilizers.',
      'Clozapine module — titration, FBC monitoring, ANC/WBC checker, rechallenge, community criteria.',
      'LAI depot module — Sustenna, Maintena, Trinza initiation + missed dose algorithms.',
      'Mood stabilizer module — drug profiles + lithium taper.',
      'QTc stacker for cumulative cardiac risk.',
      'Ramadan mode for fasting-aware dosing.',
      'In-app reviewer sign-off workflow.',
    ],
  },
];
