include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    require_trailing_commas: true
    public_member_api_docs: false
    sort_pub_dependencies: false
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
    avoid_print: false # build-time / server-time CLI tool — print is fine
