// Plain-language counselling card formatter.
//
// Pure Dart — no Flutter imports. Mirrors RN
// `utils/formatDischarge.ts` `formatCounsellingCard`. Generates a
// patient-facing handout from the engine output: a week-by-week
// schedule, "what you may feel" bullets, and "when to call your
// clinic" red-flag list. No LLM, no async — pure template.

import 'package:psychswitch_engine/switching_engine.dart';
import 'package:psychswitch_engine/types/drug.dart';
import 'package:psychswitch_engine/types/schedule_step.dart';

/// Build the counselling card for a SwitchPlanOk.
String formatCounsellingCard({
  required Drug fromDrug,
  required Drug toDrug,
  required SwitchPlanOk plan,
}) {
  final durationDays = plan.rule.durationDays;
  final lines = <String>[
    'Your medication change',
    '',
    'Over the next $durationDays days your doctor is adjusting your medication. You are moving from ${fromDrug.genericName} to ${toDrug.genericName}. Here is what to expect, week by week.',
    '',
  ];

  final weeks = _groupByWeek(plan.schedule);
  for (var i = 0; i < weeks.length; i++) {
    final week = weeks[i];
    final first = week.first;
    final last = week.last;
    final range = first.day == last.day
        ? 'Day ${first.day}'
        : 'Days ${first.day}–${last.day}';
    lines.add('Week ${i + 1} ($range):');
    for (final step in week) {
      lines.add('  • ${_stepInPlainLanguage(step, fromDrug, toDrug)}');
    }
    lines.add('');
  }

  final guidance = _patientGuidance(fromDrug, toDrug);
  if (guidance.isNotEmpty) {
    lines.add('What you may feel:');
    for (final g in guidance) {
      lines.add('  • $g');
    }
    lines.add('');
  }

  lines
    ..add('When to call your clinic:')
    ..add('  • Severe dizziness, fainting, or palpitations')
    ..add('  • Worsening mood or thoughts of self-harm')
    ..add('  • Severe nausea, vomiting, or rash')
    ..add('  • Anything that feels wrong or alarming')
    ..add('');

  if (!plan.dosesMatchReference) {
    lines
      ..add(
        'Note: this plan was tailored to your current doses. Take only '
        'the doses written on your prescription.',
      )
      ..add('');
  }

  lines.add(
    '— Generated by PsychSwitch as a guide. Always follow the doses '
    'your doctor has prescribed.',
  );
  return lines.join('\n');
}

List<List<ScheduleStep>> _groupByWeek(List<ScheduleStep> schedule) {
  final groups = <List<ScheduleStep>>[];
  if (schedule.isEmpty) return groups;
  var current = <ScheduleStep>[];
  var weekStart = (schedule.first.day - 1) ~/ 7;
  for (final s in schedule) {
    final wk = (s.day - 1) ~/ 7;
    if (wk != weekStart && current.isNotEmpty) {
      groups.add(current);
      current = <ScheduleStep>[];
      weekStart = wk;
    }
    current.add(s);
  }
  if (current.isNotEmpty) groups.add(current);
  return groups;
}

String _stepInPlainLanguage(
  ScheduleStep step,
  Drug fromDrug,
  Drug toDrug,
) {
  if (step.fromDoseMg == 0 && step.toDoseMg > 0) {
    return 'Stop ${fromDrug.genericName}. '
        'Take ${toDrug.genericName} ${_fmt(step.toDoseMg)} mg.';
  }
  if (step.fromDoseMg > 0 && step.toDoseMg == 0) {
    return 'Take ${fromDrug.genericName} ${_fmt(step.fromDoseMg)} mg.';
  }
  return 'Take ${fromDrug.genericName} ${_fmt(step.fromDoseMg)} mg '
      'and ${toDrug.genericName} ${_fmt(step.toDoseMg)} mg.';
}

List<String> _patientGuidance(Drug fromDrug, Drug toDrug) {
  // Generic by-class messages — keeps the card useful even without
  // per-drug richness. Errs on the side of reassurance + safety
  // signposting.
  // ignore_for_file: no_adjacent_strings_in_list — wrapped sentences.
  final out = <String>[
    'Some mild dizziness, headache, or stomach upset is common in '
        'the first few days as your body adjusts.',
    'Sleep changes can happen during a switch — give it a week before '
        'changing routines.',
  ];
  if (toDrug.drugClass.toLowerCase().contains('ssri') ||
      toDrug.drugClass.toLowerCase().contains('snri')) {
    out.add(
      'It can take 2–6 weeks for the new medicine to settle in. '
      'Mood may briefly worsen before improving.',
    );
  }
  if (fromDrug.drugClass.toLowerCase().contains('ssri') ||
      fromDrug.drugClass.toLowerCase().contains('snri')) {
    out.add(
      'Stopping the previous medicine too quickly can cause flu-like '
      'feelings, "brain zaps", or vivid dreams. The taper schedule is '
      'designed to minimise this.',
    );
  }
  return out;
}

String _fmt(num n) {
  if (n is int || n == n.toInt()) return n.toInt().toString();
  return n.toString();
}
