// Plain-text formatter for the cross-taper plan, suitable for the
// native share sheet (WhatsApp, SMS, email). Mirrors the RN
// `utils/sharePlan.ts` output so a clinician sharing the same case
// from RN vs Flutter sees an identical message.
//
// Pure Dart — no Flutter imports. Trivially unit-testable.

import 'package:psychswitch_engine/switching_engine.dart';
import 'package:psychswitch_engine/types/drug.dart';
import 'package:psychswitch_engine/types/enums.dart';

const Map<String, String> _strategyDisplay = <String, String>{
  'direct': 'Direct switch',
  'cross-taper': 'Cross-taper',
  'plateau-cross-taper': 'Plateau cross-taper',
  'overlap-taper': 'Overlap taper',
  'washout': 'Washout',
};

/// Trim the internal audit suffix before including text in shares.
String _cleanText(String text) =>
    text.replaceAll(RegExp(r'\s*PENDING_CLINICAL_REVIEW\.?\s*$'), '').trim();

String _formatDose(num n) {
  if (n is int || n == n.toInt()) return n.toInt().toString();
  return n.toString();
}

/// Format a reviewed cross-taper plan for sharing via the native share
/// sheet. Includes header, dose mapping, day-by-day schedule with step
/// notes, monitoring checklist (severity-tinted via emoji prefix), and
/// citations.
String formatPlanForShare({
  required Drug fromDrug,
  required Drug toDrug,
  required SwitchPlanOk plan,
}) {
  final totalDays = plan.rule.durationDays;
  final strategyKey = plan.rule.strategy.jsonValue;
  final strategyLabel = _strategyDisplay[strategyKey] ?? strategyKey;
  final lines = <String>[
    // ── Header ────────────────────────────────────────────────────
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'PsychSwitch — Cross-taper plan',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '${fromDrug.genericName} → ${toDrug.genericName}',
    '$strategyLabel · $totalDays days',
    '',

    // ── Dose mapping ──────────────────────────────────────────────
    'DOSE MAPPING',
    // ignore: no_adjacent_strings_in_list — single conceptual sentence wrapped.
    '${fromDrug.genericName} ${_formatDose(plan.rule.doseRatios.fromCurrentDoseMg)} mg ≈ ${toDrug.genericName} ${_formatDose(plan.rule.doseRatios.toTargetDoseMg)} mg',
  ];
  final equivNote = _cleanText(plan.rule.doseRatios.equivalencyNote);
  if (equivNote.isNotEmpty) lines.add('  $equivNote');
  if (!plan.dosesMatchReference) {
    lines.add(
      '  Note: You entered ${_formatDose(plan.inputDoses.fromMg)} mg → '
      '${_formatDose(plan.inputDoses.toMg)} mg. Schedule below is the '
      'reviewed reference — adapt doses proportionally.',
    );
  }
  lines.add('');

  // ── Rationale ───────────────────────────────────────────────────
  final rationale = _cleanText(plan.rule.rationale);
  if (rationale.isNotEmpty) {
    lines
      ..add('WHY THIS STRATEGY')
      ..add(rationale.length > 300
          ? '${rationale.substring(0, 300)}…'
          : rationale)
      ..add('');
  }

  // ── Schedule ────────────────────────────────────────────────────
  lines.add('SCHEDULE');
  for (final step in plan.schedule) {
    final fromUnit = fromDrug.formulation == Formulation.lai ? 'mg/inj' : 'mg';
    final toUnit = toDrug.formulation == Formulation.lai ? 'mg/inj' : 'mg';
    final fromLabel = step.fromDoseMg == 0
        ? 'STOP'
        : '${_formatDose(step.fromDoseMg)} $fromUnit';
    final toLabel = step.toDoseMg == 0
        ? '—'
        : '${_formatDose(step.toDoseMg)} $toUnit';
    lines.add(
      'Day ${step.day.toString().padRight(3)}  ${fromDrug.genericName} '
      '$fromLabel  |  ${toDrug.genericName} $toLabel',
    );
    if (step.notes != null && step.notes!.isNotEmpty) {
      lines.add('         → ${step.notes}');
    }
  }
  lines.add('');

  // ── Monitoring checklist ───────────────────────────────────────
  if (plan.safetyFlags.isNotEmpty) {
    lines.add('MONITORING CHECKLIST');
    for (final key in plan.safetyFlags) {
      final prefix = key.contains('avoid') ||
              key.contains('contraindicat') ||
              key.startsWith('maoi_washout') ||
              key == 'discontinuation_syndrome_high'
          ? '🟡'
          : '🔵';
      lines.add('$prefix ${key.replaceAll('_', ' ')}');
    }
    lines.add('');
  }

  // ── Citations ───────────────────────────────────────────────────
  lines.add('REFERENCES');
  for (var i = 0; i < plan.citations.length; i++) {
    lines.add('[${i + 1}] ${plan.citations[i]}');
  }
  lines.addAll(<String>[
    'Reviewed by: ${plan.rule.reviewedBy}',
    'Last reviewed: ${plan.rule.lastReviewedISO}',
    '',
    // ── Footer ────────────────────────────────────────────────────
    '─────────────────────────────────',
    'Decision support only — not medical advice.',
    'Verify against primary references (Maudsley, BAP, NICE) and',
    "the patient's individual context before prescribing.",
    'Generated by PsychSwitch',
  ]);

  return lines.join('\n');
}

/// Format an MAOI washout plan for sharing — strict separation from
/// the cross-taper formatter so the serotonin-syndrome risk framing is
/// unmistakable.
String formatWashoutForShare({
  required Drug fromDrug,
  required Drug toDrug,
  required num fromDoseMg,
  required SwitchPlanMaoiWashout plan,
}) {
  final lines = <String>[
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'PsychSwitch — ⚠ MAOI WASHOUT REQUIRED',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '${fromDrug.genericName} ${_formatDose(fromDoseMg)} mg → ${toDrug.genericName}',
    'Washout: ${plan.washoutDays} day${plan.washoutDays == 1 ? '' : 's'}',
    '',
    '🔴 FATAL INTERACTION RISK — NO OVERLAP PERMITTED',
    plan.reason,
    '',
    'STEPS',
    '1. Day 0:  Stop ${fromDrug.genericName} ${_formatDose(fromDoseMg)} mg',
    '2. Days 1–${plan.washoutDays}: No antidepressant — complete washout',
    '3. Day ${plan.washoutDays + 1}+: Start ${toDrug.genericName} at standard initiation dose. Titrate per usual regimen.',
    '',
    'AVOID DURING WASHOUT',
    "Serotonergic agents (SSRI, SNRI, tramadol, triptans, linezolid, methylene blue, dextromethorphan, St John's wort), and tyramine-rich foods if MAOI was the from-drug.",
    '',
  ];

  if (plan.safetyFlags.isNotEmpty) {
    lines.add('SAFETY FLAGS');
    for (final key in plan.safetyFlags) {
      lines.add('🔴 ${key.replaceAll('_', ' ')}');
    }
    lines.add('');
  }

  lines.addAll(<String>[
    '─────────────────────────────────',
    'Decision support only — not medical advice.',
    'Generated by PsychSwitch',
  ]);

  return lines.join('\n');
}
