// Workflow-loop output formatters.
//
// Three formats from one set of inputs:
//   1. Discharge summary  — clinician-facing, EMR-paste-ready plain text.
//   2. Counselling card   — patient-facing, plain-language explanation.
//   3. PDF HTML           — printable handout (used by expo-print).
//
// All three are pure functions of the engine output + drug profiles +
// (optionally) patient context + scaling result. No React state, no
// async — easy to unit-test, easy to share through any sheet.
import type { Drug, ScheduleStep, SwitchingRule } from '../engine/types';
import type { ScaleResult } from '../engine/scaleSchedule';
import type { MonitoringPlan } from '../engine/monitoring';
import { gradeCitations, gradeLabel, getCitation, type EvidenceGrade } from '../engine/citations';

export interface FormatInputs {
  rule: SwitchingRule;
  fromDrug: Drug;
  toDrug: Drug;
  schedule: ScheduleStep[];      // adapted (post-scaling) — what the user sees
  monitoring: MonitoringPlan;
  scaleResult: ScaleResult;
  durationDays: number;
  /** Optional case label ("Mr A — 12/7"). */
  caseLabel?: string;
}

const APP_VERSION = '0.3.1';

// ── Discharge summary ────────────────────────────────────────────────────────

/**
 * Plain-text block formatted for EMR paste. Designed to be read-friendly
 * in monospace, but also OK in proportional fonts.
 */
export function formatDischargeSummary(input: FormatInputs): string {
  const { rule, fromDrug, toDrug, schedule, monitoring, scaleResult, durationDays, caseLabel } = input;
  const grade: EvidenceGrade = gradeCitations(rule.citations);

  const lines: string[] = [];

  if (caseLabel) lines.push(`CASE: ${caseLabel}`);
  lines.push(`PLAN: ${humanStrategy(rule.strategy)} ${fromDrug.genericName} ${schedule[0]?.fromDoseMg ?? '?'} mg → ${toDrug.genericName} ${schedule[schedule.length - 1]?.toDoseMg ?? '?'} mg over ${durationDays} d.`);

  // Source line — first citation, abbreviated.
  if (rule.citations.length > 0) {
    const cit = getCitation(rule.citations[0]);
    const locator = cit.locator ? ` ${cit.locator}` : '';
    lines.push(`SOURCE: ${citationShort(cit.source)}${locator}.`);
  }

  // Adapted note
  if (scaleResult.adapted && scaleResult.applied.mode === 'proportional') {
    lines.push(
      `NOTE: Schedule adapted to entered doses (scaled ${scaleResult.applied.fromFactor.toFixed(2)}× from / ${scaleResult.applied.toFactor.toFixed(2)}× to).`,
    );
  } else if (scaleResult.applied.mode === 'no-scale' && !scaleResult.adapted) {
    lines.push('NOTE: Fixed protocol (LAI / PK-defined). Doses set by product PI.');
  }

  // Schedule
  lines.push('');
  lines.push('SCHEDULE:');
  for (const step of schedule) {
    const fromTxt = step.fromDoseMg === 0
      ? `STOP ${fromDrug.genericName}`
      : `${fromDrug.genericName} ${step.fromDoseMg} mg`;
    const toTxt = step.toDoseMg === 0
      ? '—'
      : `${toDrug.genericName} ${step.toDoseMg} mg`;
    lines.push(`  D${pad(step.day, 2)}: ${fromTxt} | ${toTxt}`);
  }

  // Monitoring
  if (monitoring.entries.length > 0) {
    lines.push('');
    lines.push('MONITORING:');
    for (const e of monitoring.entries) {
      lines.push(`  D${pad(e.dayOffset, 2)}: ${e.label} — ${e.detail}`);
    }
  }

  // Evidence + reviewer
  lines.push('');
  lines.push(`EVIDENCE: ${grade} (${gradeLabel(grade)}${scaleResult.adapted && scaleResult.evidencePenalty > 0 ? ' — adapted' : ''}).`);
  lines.push(`REVIEWED: ${rule.reviewedBy} · last reviewed ${rule.lastReviewedISO}.`);
  lines.push('');
  lines.push(`Generated by PsychSwitch v${APP_VERSION}. Decision support only — not medical advice.`);

  return lines.join('\n');
}

// ── Counselling card (patient-facing) ────────────────────────────────────────

/**
 * Plain-language version of the schedule. No drug-class jargon, no
 * "EMR" register — written to be readable by a patient or carer.
 *
 * Deliberately template-driven (not LLM). v1 keeps tone clinical-but-
 * approachable; tone tuning per locale lands when i18n content arrives.
 */
export function formatCounsellingCard(input: FormatInputs): string {
  const { rule, fromDrug, toDrug, schedule, durationDays, scaleResult } = input;

  const lines: string[] = [];
  lines.push('Your medication change');
  lines.push('');
  lines.push(
    `Over the next ${durationDays} days your doctor is adjusting your medication. You are moving from ${fromDrug.genericName} to ${toDrug.genericName}. Here is what to expect, week by week.`,
  );
  lines.push('');

  // Group schedule into rough weeks for readability.
  const weeks = groupByWeek(schedule);
  for (let i = 0; i < weeks.length; i++) {
    const week = weeks[i];
    const first = week[0];
    const last = week[week.length - 1];
    const range = first.day === last.day
      ? `Day ${first.day}`
      : `Days ${first.day}–${last.day}`;
    lines.push(`Week ${i + 1} (${range}):`);
    for (const step of week) {
      lines.push(`  • ${stepInPlainLanguage(step, fromDrug, toDrug)}`);
    }
    lines.push('');
  }

  // What to expect — generic guidance from drug profile flags.
  const guidance = patientGuidance(fromDrug, toDrug, rule);
  if (guidance.length > 0) {
    lines.push('What you may feel:');
    for (const g of guidance) lines.push(`  • ${g}`);
    lines.push('');
  }

  // When to call
  lines.push('When to call your clinic:');
  lines.push('  • Severe dizziness, fainting, or palpitations');
  lines.push('  • Worsening mood or thoughts of self-harm');
  lines.push('  • Severe nausea, vomiting, or rash');
  lines.push('  • Anything that feels wrong or alarming');
  lines.push('');

  if (scaleResult.adapted) {
    lines.push(
      'Note: this plan was tailored to your current doses. Take only the doses written on your prescription.',
    );
    lines.push('');
  }

  lines.push('— Generated by PsychSwitch as a guide. Always follow the doses your doctor has prescribed.');
  return lines.join('\n');
}

// ── PDF HTML ─────────────────────────────────────────────────────────────────

/**
 * HTML for expo-print. Self-contained (no external resources). Sized
 * for A4 portrait. Conservative typography so it renders consistently
 * across iOS & Android print pipelines.
 */
export function formatPdfHtml(input: FormatInputs): string {
  const { rule, fromDrug, toDrug, schedule, monitoring, scaleResult, durationDays, caseLabel } = input;
  const grade: EvidenceGrade = gradeCitations(rule.citations);
  const dateStr = new Date().toISOString().slice(0, 10);

  const scheduleRows = schedule.map((s) => `
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;font-family:Menlo,monospace">D${s.day}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${
        s.fromDoseMg === 0 ? `<em>STOP ${escapeHtml(fromDrug.genericName)}</em>` : `${escapeHtml(fromDrug.genericName)} <strong>${s.fromDoseMg} mg</strong>`
      }</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${
        s.toDoseMg === 0 ? '—' : `${escapeHtml(toDrug.genericName)} <strong>${s.toDoseMg} mg</strong>`
      }</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#555;font-size:11px">${
        s.notes ? escapeHtml(s.notes) : ''
      }</td>
    </tr>
  `).join('');

  const monitoringRows = monitoring.entries.map((e) => `
    <tr>
      <td style="padding:5px 10px;border-bottom:1px solid #eee;font-family:Menlo,monospace">D${e.dayOffset}</td>
      <td style="padding:5px 10px;border-bottom:1px solid #eee"><strong>${escapeHtml(e.label)}</strong></td>
      <td style="padding:5px 10px;border-bottom:1px solid #eee;color:#555;font-size:11px">${escapeHtml(e.detail)}</td>
    </tr>
  `).join('');

  const citationLis = rule.citations.map((k) => {
    const cit = getCitation(k);
    return `<li style="margin-bottom:4px">${escapeHtml(cit.reference)}${cit.locator ? ` — ${escapeHtml(cit.locator)}` : ''}</li>`;
  }).join('');

  return `
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>PsychSwitch — ${escapeHtml(fromDrug.genericName)} → ${escapeHtml(toDrug.genericName)}</title>
</head>
<body style="font-family:-apple-system,Helvetica,Arial,sans-serif;color:#0b0f14;padding:32px;max-width:780px;margin:0 auto">
  <header style="border-bottom:2px solid #0b0f14;padding-bottom:12px;margin-bottom:18px">
    <div style="display:flex;justify-content:space-between;align-items:flex-end">
      <div>
        <div style="font-size:11px;letter-spacing:2px;color:#666;text-transform:uppercase">PsychSwitch · cross-titration plan</div>
        <h1 style="font-size:22px;margin:6px 0 0 0">${escapeHtml(fromDrug.genericName)} → ${escapeHtml(toDrug.genericName)}</h1>
        <div style="color:#555;font-size:12px;margin-top:2px">${humanStrategy(rule.strategy)} · ${durationDays} days</div>
      </div>
      <div style="text-align:right;font-size:11px;color:#666">
        ${caseLabel ? `<div><strong>${escapeHtml(caseLabel)}</strong></div>` : ''}
        <div>Generated ${dateStr}</div>
        <div>Evidence ${grade} · ${gradeLabel(grade)}${scaleResult.adapted && scaleResult.evidencePenalty > 0 ? ' (adapted)' : ''}</div>
      </div>
    </div>
  </header>

  ${scaleResult.adapted && scaleResult.applied.mode === 'proportional' ? `
    <div style="background:#eef4fc;border-left:3px solid #3b82f6;padding:8px 12px;margin-bottom:14px;font-size:12px">
      <strong>Adapted to entered doses</strong> — scaled ${scaleResult.applied.fromFactor.toFixed(2)}× from / ${scaleResult.applied.toFactor.toFixed(2)}× to. Doses rounded to formulation.
    </div>
  ` : ''}

  <h2 style="font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#666;margin:18px 0 6px 0">Schedule</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:18px">
    <thead>
      <tr style="background:#f5f5f5">
        <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555;width:60px">Day</th>
        <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555">${escapeHtml(fromDrug.genericName)}</th>
        <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555">${escapeHtml(toDrug.genericName)}</th>
        <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555">Notes</th>
      </tr>
    </thead>
    <tbody>
      ${scheduleRows}
    </tbody>
  </table>

  ${monitoring.entries.length > 0 ? `
    <h2 style="font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#666;margin:18px 0 6px 0">Monitoring</h2>
    <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:18px">
      <thead>
        <tr style="background:#f5f5f5">
          <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555;width:60px">Day</th>
          <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555;width:160px">Item</th>
          <th style="text-align:left;padding:8px 10px;font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#555">Detail</th>
        </tr>
      </thead>
      <tbody>${monitoringRows}</tbody>
    </table>
  ` : ''}

  ${rule.citations.length > 0 ? `
    <h2 style="font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#666;margin:18px 0 6px 0">Sources</h2>
    <ol style="padding-left:18px;font-size:11px;color:#444;margin:0">
      ${citationLis}
    </ol>
  ` : ''}

  <footer style="margin-top:24px;padding-top:10px;border-top:1px solid #ddd;font-size:10px;color:#888;line-height:1.5">
    <div><strong>Reviewer:</strong> ${escapeHtml(rule.reviewedBy)} · Last reviewed ${escapeHtml(rule.lastReviewedISO)}</div>
    <div>Generated by PsychSwitch v${APP_VERSION} on ${dateStr}. Decision support for qualified clinicians; not medical advice. Verify against the primary source before acting.</div>
  </footer>
</body>
</html>`.trim();
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function pad(n: number, width: number): string {
  const s = String(n);
  return s.length >= width ? s : '0'.repeat(width - s.length) + s;
}

function citationShort(source: string): string {
  switch (source) {
    case 'Maudsley15': return 'Maudsley 15th';
    case 'BAP': return 'BAP guideline';
    case 'NICE': return 'NICE guideline';
    case 'FDA': return 'FDA PI';
    case 'EMA': return 'EMA PI';
    case 'CPG-MY': return 'Malaysian CPG';
    case 'meta-analysis': return 'Meta-analysis';
    case 'manufacturer': return 'Manufacturer PI';
    default: return source;
  }
}

function humanStrategy(s: string): string {
  switch (s) {
    case 'direct': return 'Direct switch';
    case 'cross-taper': return 'Cross-taper';
    case 'plateau-cross-taper': return 'Plateau cross-taper';
    case 'washout': return 'Washout';
    default: return s;
  }
}

function groupByWeek(schedule: ScheduleStep[]): ScheduleStep[][] {
  const weeks: ScheduleStep[][] = [];
  for (const step of schedule) {
    const weekIndex = Math.floor((step.day - 1) / 7);
    while (weeks.length <= weekIndex) weeks.push([]);
    weeks[weekIndex].push(step);
  }
  return weeks.filter((w) => w.length > 0);
}

function stepInPlainLanguage(step: ScheduleStep, fromDrug: Drug, toDrug: Drug): string {
  const fromVerb = step.fromDoseMg === 0
    ? `Stop ${fromDrug.genericName}`
    : `Take ${fromDrug.genericName} ${step.fromDoseMg} mg`;
  const toVerb = step.toDoseMg === 0
    ? null
    : `take ${toDrug.genericName} ${step.toDoseMg} mg`;
  return [fromVerb, toVerb].filter(Boolean).join('; ') + '.';
}

function patientGuidance(fromDrug: Drug, toDrug: Drug, _rule: SwitchingRule): string[] {
  const out: string[] = [];
  // Sedation
  const sed = (toDrug as { sedation?: string }).sedation;
  if (sed === 'high' || sed === 'very high') {
    out.push(`${toDrug.genericName} can make you feel sleepy — take it at bedtime if your prescription allows.`);
  }
  // Discontinuation risk
  const disc = (fromDrug as { discontinuationSyndromeRisk?: { score?: string } }).discontinuationSyndromeRisk;
  if (disc?.score === 'high' || disc?.score === 'very high') {
    out.push(`Stopping ${fromDrug.genericName} suddenly can cause dizziness or flu-like feelings. Follow the gradual reduction in this plan exactly.`);
  }
  // QT risk
  const qtc = (toDrug as { qtcRisk?: string }).qtcRisk;
  if (qtc === 'high' || qtc === 'very high') {
    out.push(`Your doctor will check your heart tracing (ECG) during this change.`);
  }
  // Generic
  out.push('Side effects often settle in the first 1–2 weeks. Keep taking the medication as prescribed.');
  return out;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
