// Patient context — pure types and helpers.
//
// Mirrors engine/patientContextPure.ts. Kept free of any Flutter / SDK
// imports so the same warning logic can be reused on every surface
// (engine, MCP server, integration tests).
//
// IMPORTANT — keep this file pure:
//   • No imports from `package:flutter/...`
//   • No top-level side effects.
//   • If you need stateful behaviour, add it next to the Riverpod
//     provider that wraps this module, not here.

/// Coarse age binning used by the warning matrix.
enum AgeBand {
  pediatric('pediatric'),
  adult('adult'),
  olderAdult('older_adult');

  const AgeBand(this.jsonValue);

  final String jsonValue;
}

/// Renal-function band (K/DOQI tiers, simplified).
enum RenalFn {
  normal('normal'),
  mild('mild'),
  moderate('moderate'),
  severe('severe');

  const RenalFn(this.jsonValue);

  final String jsonValue;
}

/// Hepatic-function band (Child-Pugh-derived, simplified).
enum HepaticFn {
  normal('normal'),
  mild('mild'),
  moderate('moderate'),
  severe('severe');

  const HepaticFn(this.jsonValue);

  final String jsonValue;
}

enum Sex {
  male('male'),
  female('female'),
  other('other');

  const Sex(this.jsonValue);

  final String jsonValue;
}

/// Severity levels for [ContextWarning].
enum WarningSeverity {
  info('info'),
  warning('warning'),
  danger('danger');

  const WarningSeverity(this.jsonValue);

  final String jsonValue;
}

/// Optional comorbidity flags.
class Comorbidities {
  const Comorbidities({
    this.cardiac,
    this.seizure,
    this.diabetes,
    this.obesity,
    this.dyslipidemia,
  });

  final bool? cardiac;
  final bool? seizure;
  final bool? diabetes;
  final bool? obesity;
  final bool? dyslipidemia;
}

/// All patient-context fields used by the engine. Every field is optional
/// — partial contexts are valid; warnings narrow accordingly.
class PatientContext {
  const PatientContext({
    this.ageYears,
    this.sex,
    this.weightKg,
    this.heightCm,
    this.renal,
    this.egfr,
    this.hepatic,
    this.pregnant,
    this.trimester,
    this.breastfeeding,
    this.smoker,
    this.comorbidities,
  });

  final num? ageYears;
  final Sex? sex;
  final num? weightKg;
  final num? heightCm;
  final RenalFn? renal;

  /// eGFR in mL/min/1.73m².
  final num? egfr;

  final HepaticFn? hepatic;
  final bool? pregnant;

  /// Trimester (1, 2, or 3) when [pregnant] is true.
  final int? trimester;

  final bool? breastfeeding;

  /// Smoking — major CYP1A2 inducer (clozapine, olanzapine clearance ↑).
  final bool? smoker;

  final Comorbidities? comorbidities;
}

/// Empty patient context — convenient default value.
const PatientContext emptyContext = PatientContext();

/// Bin [PatientContext.ageYears] into an [AgeBand]. Returns `null` when
/// age is unknown.
AgeBand? ageBand(PatientContext ctx) {
  final a = ctx.ageYears;
  if (a == null) return null;
  if (a < 18) return AgeBand.pediatric;
  if (a >= 65) return AgeBand.olderAdult;
  return AgeBand.adult;
}

/// Body-mass index in kg/m². Returns `null` when weight or height missing.
num? bmi(PatientContext ctx) {
  if (ctx.weightKg == null || ctx.heightCm == null) return null;
  final m = ctx.heightCm! / 100;
  return ctx.weightKg! / (m * m);
}

/// Estimate eGFR. Returns the explicit value if provided; otherwise
/// `null` because Cockcroft-Gault requires serum creatinine which the
/// context does not carry.
num? estimateEgfr(PatientContext ctx) => ctx.egfr;

/// Map an eGFR value to a [RenalFn] band per simplified K/DOQI.
RenalFn renalBandFromEgfr(num egfr) {
  if (egfr >= 90) return RenalFn.normal;
  if (egfr >= 60) return RenalFn.mild;
  if (egfr >= 30) return RenalFn.moderate;
  return RenalFn.severe;
}

/// Whether the context has the minimum fields the warning matrix needs.
bool isComplete(PatientContext ctx) =>
    ctx.ageYears != null && ctx.sex != null;

/// One warning generated by [warningsForDrug].
class ContextWarning {
  const ContextWarning({
    required this.severity,
    required this.message,
    this.drugId,
  });

  final WarningSeverity severity;
  final String? drugId;
  final String message;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'severity': severity.jsonValue,
        if (drugId != null) 'drugId': drugId,
        'message': message,
      };
}

/// Given a patient context and a drug, produce a list of dose-adjustment
/// or contraindication warnings. Used by the switching engine, the
/// equivalency screen, and the MCP server.
List<ContextWarning> warningsForDrug(
  PatientContext ctx,
  String drugId,
) {
  final out = <ContextWarning>[];
  final band = ageBand(ctx);
  final renal = ctx.renal ??
      (ctx.egfr != null ? renalBandFromEgfr(ctx.egfr!) : null);

  // Older-adult sedation / falls
  if (band == AgeBand.olderAdult) {
    if (<String>[
      'olanzapine',
      'quetiapine',
      'mirtazapine',
      'clozapine',
    ].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.warning,
          drugId: drugId,
          message:
              'Older adult: start at 25–50% of adult dose; review fall risk.',
        ),
      );
    }
  }

  // Pediatric
  if (band == AgeBand.pediatric) {
    out.add(
      ContextWarning(
        severity: WarningSeverity.warning,
        drugId: drugId,
        message:
            'Pediatric prescribing: most psychotropics are off-label <18. Specialist input recommended.',
      ),
    );
  }

  // Renal
  if (renal == RenalFn.moderate || renal == RenalFn.severe) {
    if (drugId == 'amisulpride' ||
        drugId == 'sulpiride' ||
        drugId == 'paliperidone') {
      final isSevere = renal == RenalFn.severe;
      out.add(
        ContextWarning(
          severity:
              isSevere ? WarningSeverity.danger : WarningSeverity.warning,
          drugId: drugId,
          message:
              'Renal clearance — reduce dose ${isSevere ? '≥50%' : '~25%'} or choose alternative.',
        ),
      );
    }
    if (drugId == 'lithium') {
      out.add(
        ContextWarning(
          severity: WarningSeverity.danger,
          drugId: drugId,
          message:
              'Lithium: contraindicated in moderate-severe CKD. Choose alternative mood stabilizer.',
        ),
      );
    }
  }

  // Hepatic
  if (ctx.hepatic == HepaticFn.moderate ||
      ctx.hepatic == HepaticFn.severe) {
    if (<String>[
      'valproate',
      'carbamazepine',
      'duloxetine',
      'agomelatine',
    ].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.danger,
          drugId: drugId,
          message:
              'Hepatic impairment: hepatotoxicity risk — avoid or use with frequent LFTs.',
        ),
      );
    }
  }

  // Pregnancy
  if (ctx.pregnant ?? false) {
    if (drugId == 'valproate') {
      out.add(
        const ContextWarning(
          severity: WarningSeverity.danger,
          drugId: 'valproate',
          message:
              'Valproate in pregnancy: 30–40% major malformation rate. Contraindicated; switch urgently.',
        ),
      );
    }
    if (drugId == 'carbamazepine') {
      out.add(
        const ContextWarning(
          severity: WarningSeverity.warning,
          drugId: 'carbamazepine',
          message:
              'Carbamazepine: neural tube defects 1%. Folate 5 mg/day. Consider alternative.',
        ),
      );
    }
    if (drugId == 'paroxetine') {
      out.add(
        const ContextWarning(
          severity: WarningSeverity.warning,
          drugId: 'paroxetine',
          message:
              'Paroxetine in 1st trimester: cardiac defect signal. Avoid if possible.',
        ),
      );
    }
    if (drugId == 'lithium' && ctx.trimester == 1) {
      out.add(
        const ContextWarning(
          severity: WarningSeverity.warning,
          drugId: 'lithium',
          message:
              'Lithium 1st trimester: small Ebstein anomaly risk. Fetal echo at 18–20w.',
        ),
      );
    }
  }

  // Breastfeeding
  if (ctx.breastfeeding ?? false) {
    if (<String>['lithium', 'clozapine', 'lamotrigine'].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.warning,
          drugId: drugId,
          message:
              'Breastfeeding: high transfer / case reports. Monitor infant; consider alternative.',
        ),
      );
    }
  }

  // Smoking — clearance modifier (CYP1A2 induction)
  if (ctx.smoker ?? false) {
    if (<String>['clozapine', 'olanzapine'].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.info,
          drugId: drugId,
          message:
              'Smoking induces CYP1A2 → up to 50% lower plasma level. Doses ↓ if smoking stops.',
        ),
      );
    }
  }

  final como = ctx.comorbidities;

  // Cardiac comorbidity + QTc-prolongers
  if (como?.cardiac ?? false) {
    if (<String>[
      'haloperidol',
      'chlorpromazine',
      'sulpiride',
      'amisulpride',
      'citalopram',
      'escitalopram',
    ].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.warning,
          drugId: drugId,
          message:
              'Cardiac history + QTc-prolonging agent. Baseline + on-treatment ECG.',
        ),
      );
    }
  }

  // Diabetes / metabolic + olanzapine, clozapine, quetiapine
  if ((como?.diabetes ?? false) || (como?.dyslipidemia ?? false)) {
    if (<String>['olanzapine', 'clozapine', 'quetiapine'].contains(drugId)) {
      out.add(
        ContextWarning(
          severity: WarningSeverity.warning,
          drugId: drugId,
          message:
              'Metabolic risk + high-metabolic agent. Prefer aripiprazole/lurasidone if possible.',
        ),
      );
    }
  }

  // Seizure + clozapine
  if (como?.seizure ?? false) {
    if (drugId == 'clozapine') {
      out.add(
        const ContextWarning(
          severity: WarningSeverity.warning,
          drugId: 'clozapine',
          message:
              'Seizure history: clozapine lowers threshold. EEG, slow titration.',
        ),
      );
    }
  }

  return out;
}
