// Runtime content loader.
//
// Reads `assets/content_bundle.json` (generated by `tool/bundle_content.dart`)
// via the Flutter rootBundle and decodes it into the typed engine
// payload — drugs, rules, Maudsley matrix, QTc, clozapine and
// mood-stabilizer content.
//
// Production path uses `compute()` to run the decode in a background
// isolate — keeps cold-start frame budget intact even on slower
// devices. The pure synchronous `decodeContentBundle` is preserved
// for unit tests + the test-only sibling loader.
//
// Failure mode is "throw at startup": if the bundle is malformed, the
// app cannot function clinically and should crash visibly rather than
// run with a half-loaded registry.

import 'dart:convert';

import 'package:flutter/foundation.dart' show compute;
import 'package:flutter/services.dart' show AssetBundle, rootBundle;

import 'package:psychswitch_engine/clozapine.dart';
import 'package:psychswitch_engine/maudsley15.dart';
import 'package:psychswitch_engine/mood_stabilizer_tapering.dart';
import 'package:psychswitch_engine/qtc_stacker.dart';
import 'package:psychswitch_engine/ramadan.dart';
import 'package:psychswitch_engine/switching_engine.dart';
import 'package:psychswitch_engine/types/drug.dart';
import 'package:psychswitch_engine/types/switching_rule.dart';

/// Path to the asset bundle inside the Flutter package.
const String contentBundleAsset = 'assets/content_bundle.json';

/// 7 LAI rules ship object-shape safetyFlags rather than the typed
/// string array (see `docs/POST_FLUTTER_DEBT.md`). Skipped at load
/// time so the engine boots; the rest of the registry is unaffected.
const Set<String> _skippedRuleIds = <String>{
  'aripiprazole-lai-to-aripiprazole',
  'flupenthixol-lai-to-flupenthixol',
  'fluphenazine-lai-to-fluphenazine',
  'haloperidol-lai-to-haloperidol',
  'paliperidone-lai-to-paliperidone',
  'risperidone-lai-to-risperidone',
  'zuclopenthixol-lai-to-zuclopenthixol',
};

/// Parsed view of the full content bundle. Phase 4 wires this into a
/// Riverpod provider; phases 5+ consume it from screens.
class LoadedContent {
  const LoadedContent({
    required this.engine,
    required this.qtcData,
    required this.lithiumTapering,
    required this.clozapine,
    required this.ramadan,
  });

  final SwitchingEngine engine;
  final QtcRiskData qtcData;
  final TaperingProtocol lithiumTapering;
  final ClozapineModule clozapine;
  final RamadanData ramadan;
}

/// Decode a pre-loaded bundle string. Pure — useful for tests.
LoadedContent decodeContentBundle(String raw) {
  final root = jsonDecode(raw) as Map<String, dynamic>;

  final drugs = (root['drugs'] as Map<String, dynamic>)
      .values
      .cast<Map<String, dynamic>>()
      .map(Drug.fromJson)
      .toList()
    ..sort((a, b) => a.id.compareTo(b.id));

  final rules = <SwitchingRule>[];
  for (final entry in (root['switching-rules'] as Map<String, dynamic>)
      .entries) {
    if (_skippedRuleIds.contains(entry.key)) continue;
    rules.add(SwitchingRule.fromJson(entry.value as Map<String, dynamic>));
  }
  rules.sort((a, b) => a.id.compareTo(b.id));

  final maudsley = Maudsley15Data.fromJson(
    root['maudsley15'] as Map<String, dynamic>,
  );

  final qtc = QtcRiskData.fromJson(root['qtc'] as Map<String, dynamic>);

  final lithium = TaperingProtocol.fromJson(
    (root['mood-stabilizers'] as Map<String, dynamic>)['lithium-tapering']
        as Map<String, dynamic>,
  );

  final cloz = root['clozapine'] as Map<String, dynamic>;
  final clozapineModule = ClozapineModule(
    ClozapineContent(
      femaleNonSmoker: TitrationProtocol.fromJson(
        cloz['titration-female-non-smoker'] as Map<String, dynamic>,
      ),
      femaleSmoker: TitrationProtocol.fromJson(
        cloz['titration-female-smoker'] as Map<String, dynamic>,
      ),
      maleNonSmoker: TitrationProtocol.fromJson(
        cloz['titration-male-non-smoker'] as Map<String, dynamic>,
      ),
      maleSmoker: TitrationProtocol.fromJson(
        cloz['titration-male-smoker'] as Map<String, dynamic>,
      ),
      monitoringSchedule: MonitoringScheduleData.fromJson(
        cloz['monitoring-schedule'] as Map<String, dynamic>,
      ),
      safetyConsiderations: SafetyConsiderationsData.fromJson(
        cloz['safety-considerations'] as Map<String, dynamic>,
      ),
      rechallengeRules: RechallengeRulesData.fromJson(
        cloz['rechallenge-rules'] as Map<String, dynamic>,
      ),
      communityInitiation: CommunityInitiationData.fromJson(
        cloz['community-initiation'] as Map<String, dynamic>,
      ),
    ),
  );

  final ramadan = RamadanData.fromJson(
    root['ramadan'] as Map<String, dynamic>,
  );

  return LoadedContent(
    engine: SwitchingEngine(
      drugs: drugs,
      rules: rules,
      maudsley15Data: maudsley,
    ),
    qtcData: qtc,
    lithiumTapering: lithium,
    clozapine: clozapineModule,
    ramadan: ramadan,
  );
}

/// Production loader — reads the bundle via [rootBundle] and decodes
/// it on a background isolate via `compute()` so cold-start animations
/// stay buttery on slow devices. Pass [bundle] to override (e.g. test
/// asset stub).
///
/// In test environments where isolates are unavailable, [decodeOnMain]
/// can be set to true — `decodeContentBundle` runs on the current
/// isolate. Existing tests pass `bundle:` and rely on this fallback
/// implicitly via [_safeCompute].
Future<LoadedContent> loadContent({
  AssetBundle? bundle,
  bool decodeOnMain = false,
}) async {
  final raw = await (bundle ?? rootBundle).loadString(contentBundleAsset);
  if (decodeOnMain) return decodeContentBundle(raw);
  return _safeCompute(raw);
}

/// `compute()` requires the platform message loop to be running. In
/// `flutter_test`'s default isolate the binary messenger is mocked,
/// which means `compute` either hangs or runs on main depending on
/// the Flutter version. We guard against both: try the isolate path,
/// fall back to a synchronous decode if it throws.
Future<LoadedContent> _safeCompute(String raw) async {
  try {
    return await compute(decodeContentBundle, raw);
  } on Object {
    return decodeContentBundle(raw);
  }
}
